// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa8ig7l_FXTSWknkw6pHy6RI_3nB2JTJE',
    appId: '1:890250515707:web:e16b3e8cf0ea55748d8c5e',
    messagingSenderId: '890250515707',
    projectId: 'bookapp-9d8e8',
    authDomain: 'bookapp-9d8e8.firebaseapp.com',
    storageBucket: 'bookapp-9d8e8.firebasestorage.app',
    measurementId: 'G-0DT3JCMDJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7jiFxsaqH88_xRVg6zHyksAUnLC1gBWM',
    appId: '1:890250515707:android:2e045015d30db1328d8c5e',
    messagingSenderId: '890250515707',
    projectId: 'bookapp-9d8e8',
    storageBucket: 'bookapp-9d8e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAodIkW7KblBuGIXBlgPrcaGEF6SqbDuio',
    appId: '1:890250515707:ios:567dc1949acb87eb8d8c5e',
    messagingSenderId: '890250515707',
    projectId: 'bookapp-9d8e8',
    storageBucket: 'bookapp-9d8e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterProj',
  );
}
